# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Y4rd13
          template: classic
          base: header, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: America/Santiago
          config_twemoji: yes
          
          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          # Discussions
          plugin_discussions: yes
          plugin_discussions_categories: yes
          
          # Followup
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          
          # Habits
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 11
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Lines
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # People
          plugin_people: yes
          plugin_people_limit: 30
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          # Repositories
          plugin_repositories: yes
          plugin_repositories_order: pinned, random
          
          # Sponsors
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          
          # Topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          
          # Traffic
          plugin_traffic: yes
