# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (once a week)
  schedule: [{ cron: "0 0 * * 0" }]
  ## Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Plugins: options
          user: Y4rd13
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Santiago

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # Followup
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Lines
          plugin_lines: yes

          # People
          plugin_people: yes
          plugin_people_limit: 30
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Projects
          plugin_projects: yes
          plugin_projects_limit: 4

          # Skyline
          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_skyline_year: current-year

          # Topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars

          # Traffic
          plugin_traffic: yes

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 11
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
